version: "3.8"
# include:
#   - oidc-casdoor\docker-compose.yml
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/sqllite.db:/app/test.db
      - ./backend/review_history.json:/app/review_history.json

      # - type: bind
      #   source: ./backend/.cache/pypoetry
      #   target: /root/.cache/pypoetry

      
      - type: bind
        source: ./backend/.cache/huggingface/hub/models--bert-base-uncased
        target: /root/.cache/huggingface/hub/models--bert-base-uncased
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"]
    # command: ["sleep", "infinity"]

    environment:
      - OPENSEARCH_HOST=opensearch
      - LLM_Endpoint=http://host.docker.internal:11434
    networks:
      - default
  frontend:
    volumes:
      - ./tmp/nginx:/tmp/nginx
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"] # Checks if the NGINX server is running
      interval: 1m30s # Run the check every 90 seconds
      timeout: 10s # Allow up to 10 seconds for the check to complete
      retries: 3 # Try up to 3 times before marking the container as unhealthy

  nginx:
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - casdoor
      # - db
    networks:
      - default
    volumes:
      - type: bind
        source: ./ssl
        target: /tmp/nginx/ssl

  casdoor:
    extends:
      file: oidc-casdoor\docker-compose.yml
      service: casdoor
    networks:
      - default

  # db:
  #   extends:
  #     file: oidc-casdoor\docker-compose.yml
  #     service: db
  #   networks:
  #     - default

  # vllm:
  #   image: vllm/vllm-openai
  #   restart: unless-stopped
  #   environment:
  #     - HUGGING_FACE_HUB_TOKEN=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
  #   ports:
  #     - "8888:8080"
  #   volumes:
  #     - ./data:/data
  #     - ./.cache:/root/.cache
  #   command:
  #     - --model 
  #     - Orenguteng/Llama-3.1-8B-Lexi-Uncensored-V2
  #     - --device
  #     - "cpu"
  #     - --max-model-len
  #     - "512"
  

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  net:
    driver: bridge