version: '3.1'
services:
  casdoor:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"] # Checks if the NGINX server is running
      interval: 1m30s # Run the check every 90 seconds
      timeout: 10s # Allow up to 10 seconds for the check to complete
      retries: 3 # Try up to 3 times before marking the container as unhealthy

    restart: always
    image: casbin/casdoor-all-in-one:latest
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8008:8000"
    # depends_on:
    #   - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
  # db:
  #   restart: always
  #   image: mysql:8.0.25
  #   platform: linux/amd64
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #   volumes:
  #     - /usr/local/docker/mysql:/var/lib/mysql
  #   healthcheck:
  #       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #       timeout: 20s
  #       retries: 10
